# Generated by Django 4.2.20 on 2025-04-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_model', models.CharField(choices=[('tiny', 'Tiny'), ('base', 'Base'), ('turbo', 'Turbo'), ('small', 'Small'), ('medium', 'Medium'), ('large-v3', 'Large')], default='large-v3', max_length=10)),
            ],
        ),
    ]
