# Generated by Django 4.2.20 on 2025-04-09 18:05

from django.db import migrations, models
import whispercli.models


class Migration(migrations.Migration):

    dependencies = [
        ('whispercli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodocument',
            name='original_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='uploaded_file',
            field=models.FileField(upload_to=whispercli.models.AudioDocument.calc_name),
        ),
    ]
