# Generated by Django 4.2.20 on 2025-04-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispercli', '0003_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='audio_document',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='whispercli.audiodocument'),
            preserve_default=False,
        ),
    ]
