# Generated by Django 4.2.20 on 2025-04-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispercli', '0004_transcription_audio_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='model',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('base', 'Base'), ('turbo', 'Turbo'), ('small', 'Small'), ('medium', 'Medium'), ('large-v3', 'Large')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
