# Generated by Django 4.2.20 on 2025-04-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispercli', '0005_transcription_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transcription',
            constraint=models.UniqueConstraint(fields=('audio_document_id', 'model'), name='unique_transcription'),
        ),
    ]
