# Generated by Django 4.2.20 on 2025-04-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispercli', '0006_transcription_unique_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='json_data',
            field=models.JSONField(blank=True, null=True, verbose_name='TranscriptionData'),
        ),
    ]
